-- CREATE DATABASE BidDB;
--
-- USE BidDB;
--
-- CREATE TABLE BID (
--      id INT NOT NULL AUTO_INCREMENT,
--      user_id INT NOT NULL,
--      item_id INT NOT NULL,
--      amount DECIMAL(12, 4) NOT NULL,
--      timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--      PRIMARY KEY (id)
-- );
--
-- INSERT INTO BID (user_id, item_id, amount) VALUES (1, 100, 10.00);
-- INSERT INTO BID (user_id, item_id, amount) VALUES (2, 101, 20.50);
-- INSERT INTO BID (user_id, item_id, amount) VALUES (3, 102, 5.25);
-- INSERT INTO BID (user_id, item_id, amount) VALUES (4, 103, 15.75);
-- INSERT INTO BID (user_id, item_id, amount) VALUES (5, 104, 30.00);
--
--
