// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: forward_bid.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ForwardBidClient is the client API for ForwardBid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardBidClient interface {
	PlaceBid(ctx context.Context, in *ForwardBidRequest, opts ...grpc.CallOption) (*ForwardBidResponse, error)
}

type forwardBidClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardBidClient(cc grpc.ClientConnInterface) ForwardBidClient {
	return &forwardBidClient{cc}
}

func (c *forwardBidClient) PlaceBid(ctx context.Context, in *ForwardBidRequest, opts ...grpc.CallOption) (*ForwardBidResponse, error) {
	out := new(ForwardBidResponse)
	err := c.cc.Invoke(ctx, "/proto.ForwardBid/PlaceBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardBidServer is the server API for ForwardBid service.
// All implementations must embed UnimplementedForwardBidServer
// for forward compatibility
type ForwardBidServer interface {
	PlaceBid(context.Context, *ForwardBidRequest) (*ForwardBidResponse, error)
	mustEmbedUnimplementedForwardBidServer()
}

// UnimplementedForwardBidServer must be embedded to have forward compatible implementations.
type UnimplementedForwardBidServer struct {
}

func (UnimplementedForwardBidServer) PlaceBid(context.Context, *ForwardBidRequest) (*ForwardBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedForwardBidServer) mustEmbedUnimplementedForwardBidServer() {}

// UnsafeForwardBidServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardBidServer will
// result in compilation errors.
type UnsafeForwardBidServer interface {
	mustEmbedUnimplementedForwardBidServer()
}

func RegisterForwardBidServer(s grpc.ServiceRegistrar, srv ForwardBidServer) {
	s.RegisterService(&ForwardBid_ServiceDesc, srv)
}

func _ForwardBid_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardBidServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ForwardBid/PlaceBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardBidServer).PlaceBid(ctx, req.(*ForwardBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardBid_ServiceDesc is the grpc.ServiceDesc for ForwardBid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardBid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ForwardBid",
	HandlerType: (*ForwardBidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBid",
			Handler:    _ForwardBid_PlaceBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forward_bid.proto",
}
